### ISSUE TITLE
Cannot build on RHEL 7.3 with LLVM 3.4

### ISSUE THREAD

**Issue by athas** [Meinersbur/pencilcc#9]
```
$ make
Making all in ppcg
make[1]: Entering directory `/home/mzd885/pencilcc/ppcg'
Making all in isl
make[2]: Entering directory `/home/mzd885/pencilcc/ppcg/isl'
make  all-recursive
make[3]: Entering directory `/home/mzd885/pencilcc/ppcg/isl'
Making all in .
make[4]: Entering directory `/home/mzd885/pencilcc/ppcg/isl'
make[4]: Leaving directory `/home/mzd885/pencilcc/ppcg/isl'
Making all in interface
make[4]: Entering directory `/home/mzd885/pencilcc/ppcg/isl/interface'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/home/mzd885/pencilcc/ppcg/isl/interface'
Making all in doc
make[4]: Entering directory `/home/mzd885/pencilcc/ppcg/isl/doc'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/home/mzd885/pencilcc/ppcg/isl/doc'
make[3]: Leaving directory `/home/mzd885/pencilcc/ppcg/isl'
make[2]: Leaving directory `/home/mzd885/pencilcc/ppcg/isl'
Making all in pet
make[2]: Entering directory `/home/mzd885/pencilcc/ppcg/pet'
make  all-recursive
make[3]: Entering directory `/home/mzd885/pencilcc/ppcg/pet'
make[4]: Entering directory `/home/mzd885/pencilcc/ppcg/pet'
  CXX      inlined_calls.lo
In file included from inlined_calls.cc:38:0:
scan.h:31:8: error: redefinition of ‘struct clang::StmtRange’
 struct StmtRange : std::pair<StmtIterator,StmtIterator> {
        ^
In file included from /usr/include/clang/AST/Stmt.h:18:0,
                 from /usr/include/clang/AST/ASTTypeTraits.h:22,
                 from /usr/include/clang/AST/ASTContext.h:18,
                 from clang.h:4,
                 from inlined_calls.cc:34:
/usr/include/clang/AST/StmtIterator.h:145:8: error: previous definition of ‘struct clang::StmtRange’
 struct StmtRange : std::pair<StmtIterator,StmtIterator> {
        ^
inlined_calls.cc: In member function ‘void pet_inlined_calls::add(clang::CallExpr*)’:
inlined_calls.cc:91:11: error: ‘class clang::FunctionDecl’ has no member named ‘getReturnType’
  qt = fd->getReturnType();
           ^
```

I ran `./autogen.sh` myself and `./configure` with no options.
